M48
; DRILL file {KiCad 9.0.2} date 2025-10-22T09:47:37+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-22T09:47:37+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X133.85Y-64.8
X138.25Y-64.8
T2
X124.8Y-62.45
X125.3Y-100.6
X200.85Y-62.7
X201.0Y-100.8
M30
